version: "3.9"

services:
  weather_app:
    container_name: weather_app
    image: weather-server
    build: ./flask_dir
    ports:
      - "6000:6000"
    environment:
      - DB_URL=postgresql://postgres:postgres@weather_db:5432/postgres
    depends_on:
      - weather_db
      
  weather_db:
    container_name: weather_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
    env_file: global_variables.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - weather_db

volumes:
  pgdata: {}